name: CI pipeline for Code Quality

on:
  push:
    branches: [ "dev" , "local_stage_client" , "local_stage_server"]
  pull_request:
    branches: [ "dev" , "local_stage_client" , "local_stage_server"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Angular dependencies
        run: npm ci

      - name: Build Angular project
        run: npm run build --prod

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build and test Spring project
        run: mvn clean verify

      - name: Run code quality checks for Spring
        run: mvn checkstyle:check

      - name: Run code quality checks for Angular
        run: npx ng lint
