name: CI pipeline for Build and Quality Checks

on:
  push:
    branches: [ "dev" , "local_stage_client" , "local_stage_server"]
  pull_request:
    branches: [ "dev" , "local_stage_client" , "local_stage_server"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        grunt

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Build and test Spring project
      run: mvn clean verify

    - name: Run code quality checks for Spring
      run: mvn checkstyle:check

    - name: Run code quality checks for Angular
      run: npx ng lint
